import type { PerkDefinition, PerkId } from "./types";

const makePerkDef = (
  id: PerkId,
  name: string,
  description: string,
  category: PerkDefinition["category"],
  implemented: boolean,
): PerkDefinition => ({
  id,
  name,
  description,
  category,
  implemented,
  tiers: [
    {
      tier: 1,
      cost: 1,
      requiresLevel: 1,
      effects: [],
    },
  ],
});

export const perkDefinitions: readonly PerkDefinition[] = [
  // Combat: Planet cursor aim (implemented)
  makePerkDef(
    "combat.cursor-aim-planet",
    "Separate Aim (Planet)",
    "Aim with the mouse cursor on planets. Movement direction no longer forces facing.",
    "combat",
    true,
  ),
  makePerkDef(
    "combat.new-ammo-and-weapons",
    "New Ammunition + Weapons",
    "Unlocks exotic ammo types and weapon classes.",
    "combat",
    false,
  ),
  makePerkDef(
    "ship.new-variants",
    "New Ship Variants",
    "Unlock multiple hulls with unique handling.",
    "ship",
    false,
  ),
  makePerkDef(
    "ship.double-base-acceleration",
    "Double Base Acceleration",
    "Doubles your ship's baseline acceleration.",
    "ship",
    false,
  ),
  makePerkDef(
    "sensors.improved-radar",
    "Improved Radar",
    "Extended range and better contact discrimination.",
    "sensors",
    false,
  ),
  makePerkDef(
    "navigation.warp",
    "Warp",
    "Engage short-hop warp between distant points.",
    "navigation",
    false,
  ),
  makePerkDef(
    "cosmetic.new-paint-job",
    "Custom Paint",
    "New paint jobs and liveries for your ship.",
    "cosmetic",
    false,
  ),
  makePerkDef(
    "companions.ai-buddy",
    "AI Buddy",
    "Friendly AI wingmate that assists in combat.",
    "companions",
    false,
  ),
  makePerkDef(
    "structures.space-station",
    "Space Station",
    "Build or access a home station hub.",
    "structures",
    false,
  ),
  makePerkDef(
    "melee.melee-weapon",
    "Melee Weapon",
    "Close-quarters weapon for ramming range.",
    "melee",
    false,
  ),
  makePerkDef(
    "companions.pet-animal",
    "Pet Companion",
    "A loyal pet that rides along.",
    "companions",
    false,
  ),
  makePerkDef(
    "thrusters.strafing-thrusters",
    "Strafing Thrusters",
    "Add lateral thrusters for true strafing.",
    "thrusters",
    true,
  ),
  makePerkDef(
    "thrusters.reverse-thrusters",
    "Reverse Thrusters",
    "Dedicated reverse thrust for braking/reverse.",
    "thrusters",
    true,
  ),
  makePerkDef(
    "maneuvers.aerobatics",
    "Trick Maneuvers",
    "Loop-de-loops, rolls, and stylish aerobatics.",
    "maneuvers",
    false,
  ),
  makePerkDef("audio.radio", "Radio", "In-ship radio with vibes and chatter.", "audio", false),
  makePerkDef(
    "camera.zoom-out",
    "Zoom Out",
    "Pull the camera back for grand vistas.",
    "camera",
    false,
  ),
  makePerkDef(
    "worldgen.procedural-solar-system",
    "Procedural Solar Systems",
    "Generate star systems with planets and belts.",
    "worldgen",
    false,
  ),
  makePerkDef(
    "worldgen.procedural-environment",
    "Procedural Environments",
    "Dynamic biomes and points of interest.",
    "worldgen",
    false,
  ),
  makePerkDef(
    "multiplayer.core",
    "Multiplayer",
    "Play with friends across the stars.",
    "multiplayer",
    false,
  ),
  // New environment/mode perks
  makePerkDef(
    "environments.underground",
    "Underground",
    "Explore subterranean caverns and tunnels.",
    "environments",
    false,
  ),
  makePerkDef(
    "environments.underwater",
    "Underwater",
    "Dive beneath the waves and explore oceans.",
    "environments",
    false,
  ),
  makePerkDef(
    "environments.in-the-clouds",
    "In The Clouds",
    "Navigate sky islands and cloud cities.",
    "environments",
    false,
  ),
  // Minigames
  makePerkDef(
    "minigames.space-invaders",
    "Space Invaders Minigame",
    "Classic arcade action within your ship's console.",
    "minigames",
    false,
  ),
  // Combat enhancements
  makePerkDef(
    "combat.double-guns",
    "Double Guns",
    "Dual-wield your primary weapons for extra fire.",
    "combat",
    false,
  ),
  makePerkDef(
    "combat.heat-seeking-missiles",
    "Heat-Seeking Missiles",
    "Guided missiles that lock onto targets.",
    "combat",
    false,
  ),
  makePerkDef("combat.lasers", "Lasers", "Beam weapons with precision strikes.", "combat", false),
  // Camera / view modes
  makePerkDef(
    "camera.first-person-mode",
    "First-Person Mode",
    "Switch to immersive cockpit view.",
    "camera",
    false,
  ),
  // Companions / fleets
  makePerkDef(
    "companions.robots",
    "Robots",
    "Deploy robotic helpers for tasks or combat.",
    "companions",
    false,
  ),
  makePerkDef(
    "companions.fleets",
    "Fleets",
    "Command a small fleet to follow your lead.",
    "companions",
    false,
  ),
  // Worldgen scale
  makePerkDef("worldgen.moons", "Moons", "Introduce moons orbiting planets.", "worldgen", false),
  makePerkDef(
    "worldgen.galaxies",
    "Galaxies",
    "Travel beyond systems into galactic maps.",
    "worldgen",
    false,
  ),
  // Vehicles
  makePerkDef("vehicles.mech-suit", "Mech Suit", "Pilot a mechanized exosuit.", "vehicles", false),
  makePerkDef("vehicles.boats", "Boats", "Traverse oceans with watercraft.", "vehicles", false),
  makePerkDef(
    "vehicles.airplanes",
    "Airplanes",
    "Fixed-wing aircraft for atmospheric flight.",
    "vehicles",
    false,
  ),
  makePerkDef(
    "vehicles.blimps",
    "Blimps",
    "Leisurely airships for scenic travel.",
    "vehicles",
    false,
  ),
  // Society / economy
  makePerkDef(
    "society.peaceful-tribes",
    "Peaceful Tribes",
    "Encounter friendly tribal societies.",
    "society",
    false,
  ),
  makePerkDef("society.cities", "Cities", "Bustling urban hubs with services.", "society", false),
  makePerkDef(
    "economy.owning-property",
    "Own Property",
    "Purchase and manage personal holdings.",
    "economy",
    false,
  ),
  // Asteroids and mining
  makePerkDef(
    "world.damaging-asteroids",
    "Damaging Asteroids",
    "Asteroids can be broken with sufficient force.",
    "world",
    false,
  ),
  makePerkDef(
    "economy.asteroid-mining",
    "Asteroid Mining",
    "Extract resources from asteroids.",
    "economy",
    false,
  ),
  // Creative tools
  makePerkDef("editor.map-maker", "Map Maker", "Create and share custom maps.", "editor", false),
  makePerkDef(
    "editor.planet-designer",
    "Planet Designer",
    "Design bespoke planets with custom biomes.",
    "editor",
    false,
  ),
  makePerkDef(
    "editor.solar-system-designer",
    "Solar System Designer",
    "Craft entire solar systems from scratch.",
    "editor",
    false,
  ),
];
