name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    if: ${{ hashFiles('package.json') != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run -s typecheck

      - name: Lint
        run: npm run -s lint

      - name: Test (Vitest)
        run: npm run -s test -- --run

      - name: Build
        run: npm run -s build
